// <auto-generated />
using System;
using Entrevista2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entrevista2.Migrations
{
    [DbContext(typeof(PessoaContext))]
    [Migration("20220709222228_AlimentandoBanco")]
    partial class AlimentandoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entrevista2.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QtdFilhos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Idade = 38,
                            Nome = "Paulo",
                            QtdFilhos = 1
                        },
                        new
                        {
                            Id = 2,
                            Idade = 34,
                            Nome = "Priscila",
                            QtdFilhos = 1
                        },
                        new
                        {
                            Id = 3,
                            Idade = 36,
                            Nome = "Bruno",
                            QtdFilhos = 1
                        },
                        new
                        {
                            Id = 4,
                            Idade = 13,
                            Nome = "Julia",
                            QtdFilhos = 0
                        },
                        new
                        {
                            Id = 5,
                            Idade = 30,
                            Nome = "Pedro",
                            QtdFilhos = 1
                        },
                        new
                        {
                            Id = 6,
                            Idade = 45,
                            Nome = "Rosa",
                            QtdFilhos = 3
                        },
                        new
                        {
                            Id = 7,
                            Idade = 60,
                            Nome = "Fatima",
                            QtdFilhos = 2
                        },
                        new
                        {
                            Id = 8,
                            Idade = 31,
                            Nome = "Maria",
                            QtdFilhos = 0
                        },
                        new
                        {
                            Id = 9,
                            Idade = 20,
                            Nome = "Rodrigo",
                            QtdFilhos = 0
                        },
                        new
                        {
                            Id = 10,
                            Idade = 18,
                            Nome = "Rita",
                            QtdFilhos = 0
                        });
                });

            modelBuilder.Entity("Entrevista2.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especie = "Cachorro",
                            Nome = "Rex",
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Especie = "Cachorro",
                            Nome = "Roy",
                            PessoaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Especie = "Cachorro",
                            Nome = "Pit"
                        },
                        new
                        {
                            Id = 4,
                            Especie = "Cachorro",
                            Nome = "Tom"
                        },
                        new
                        {
                            Id = 5,
                            Especie = "Cachorro",
                            Nome = "Clark",
                            PessoaId = 4
                        },
                        new
                        {
                            Id = 6,
                            Especie = "Cachorro",
                            Nome = "Bat",
                            PessoaId = 4
                        },
                        new
                        {
                            Id = 7,
                            Especie = "Cachorro",
                            Nome = "Spider"
                        },
                        new
                        {
                            Id = 8,
                            Especie = "Gato",
                            Nome = "Mingal",
                            PessoaId = 6
                        },
                        new
                        {
                            Id = 9,
                            Especie = "Gato",
                            Nome = "Ross"
                        },
                        new
                        {
                            Id = 10,
                            Especie = "Gato",
                            Nome = "Kramer",
                            PessoaId = 6
                        },
                        new
                        {
                            Id = 11,
                            Especie = "Gato",
                            Nome = "Chandler"
                        },
                        new
                        {
                            Id = 12,
                            Especie = "Gato",
                            Nome = "Phoebe",
                            PessoaId = 8
                        },
                        new
                        {
                            Id = 13,
                            Especie = "Gato",
                            Nome = "Rachel"
                        },
                        new
                        {
                            Id = 14,
                            Especie = "Gato",
                            Nome = "Jerry",
                            PessoaId = 10
                        });
                });

            modelBuilder.Entity("Entrevista2.Models.Pet", b =>
                {
                    b.HasOne("Entrevista2.Models.Pessoa", "Pessoa")
                        .WithMany("Pets")
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Entrevista2.Models.Pessoa", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
